name: pattern_m
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  gap: ^3.0.1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.1
  file_picker: ^8.0.0+1
  pdf_text: ^0.5.0
  flutter_pdfview: ^1.3.2
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  import_sorter: ^4.6.0
  custom_lint: ^0.5.6

flutter_launcher_icons:

  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app.icon/app_icon.png"
  min_sdk_android: 21 

  windows:
    generate: true
    image_path: "assets/images/app.icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
    
  macos:
    generate: false
    image_path: "assets/images/app.icon/app_icon.png"

dependency_overrides:
  analyzer: "<=6.0.0"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/dictionary/

import_sorter:
  comments: false
